services:
  nginx:
    image: nginx
    container_name: syn-nginx
    tty: true
    ports:
      - ${NGINXPORT}:80
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server:/var/www/html
    links:
      - php-fpm
      - db
  php-fpm:
    container_name: php-fpm
    command: sh -c "composer install && git config --system --add safe.directory '/var/www/html/synesthesia_config' && git -C "synesthesia_config" pull || git clone https://github.com/BSTN/synesthesia_config && git -C "synesthesia_config" checkout ${SYNCONFIGBRANCH} && php-fpm"
    build:
      dockerfile: php-dockerfile
      context: "."
    volumes:
      - ./server:/var/www/html
    depends_on:
      - db
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DBNAME: database
      MYSQL_HOST: db
      DB_PREFIX: ""
      PASS: ${PASS}
      development: true
  app:
    image: node:14-alpine
    container_name: syn-app
    working_dir: /app
    command: sh -c "yarn install && yarn appdev"
    ports:
      - ${NODEDEVPORT-2222}:${NODEDEVPORT-2222}
    volumes:
      - type: bind
        source: ./
        target: /app
  db:
    image: mariadb
    restart: always
    container_name: mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./:/data
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: database
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
