services:
  nginx:
    image: nginx
    container_name: syn-nginx-live
    tty: true
    ports:
      - ${NGINXPORT}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server:/var/www/html
    links:
      - php-fpm
  php-fpm:
    container_name: php-fpm-live
    command: sh -c "composer install && git config --system --add safe.directory '/var/www/html/synesthesia_config' && git -C "synesthesia_config" pull || git clone https://github.com/BSTN/synesthesia_config && git -C "synesthesia_config" checkout ${SYNCONFIGBRANCH} && php-fpm"
    build:
      dockerfile: php-dockerfile
      context: "."
    volumes:
      - ./server:/var/www/html
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DBNAME: ${MYSQL_DBNAME}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      DB_PREFIX: ${DB_PREFIX}
      PASS: ${PASS}
  # db:
  #   image: mariadb
  #   restart: always
  #   container_name: mariadb
  #   volumes:
  #     - ./mariadb:/var/lib/mysql
  #     - ./:/data
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: database
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}