services:
  nginx:
    image: syn-nginx
    tty: true
    ports:
      - 80:80
    links:
      - php-fpm
  php-fpm:
    image: php-fpm
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DBNAME: ${MYSQL_DBNAME}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      DB_PREFIX: ${DB_PREFIX}
      PASS: ${PASS}