CREATE TABLE IF NOT EXISTS profile (
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UID VARCHAR(64) NOT NULL PRIMARY KEY,
  IP VARCHAR(256) DEFAULT NULL,
  language VARCHAR(2) DEFAULT NULL,
  finishedtests TEXT DEFAULT NULL,
  touchscreen TEXT DEFAULT NULL,
  USERID VARCHAR(256) DEFAULT NULL,
  SHARED VARCHAR(32) DEFAULT NULL
);
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS questions (
  ID SERIAL PRIMARY KEY,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IP VARCHAR(256) DEFAULT NULL,
  UID VARCHAR(64) NOT NULL,
  testname VARCHAR(256) DEFAULT NULL,
  setname VARCHAR(256) DEFAULT NULL,
  symbol VARCHAR(512) DEFAULT NULL,
  value VARCHAR(512) DEFAULT NULL,
  clicks INT DEFAULT NULL,
  clicksslider INT DEFAULT NULL,
  position VARCHAR(512) DEFAULT NULL,
  timing BIGINT DEFAULT NULL,
  qnr INT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS extra (
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IP VARCHAR(256) DEFAULT NULL,
  UID VARCHAR(64) NOT NULL PRIMARY KEY,
  data TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS access (
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IP VARCHAR(128) NOT NULL PRIMARY KEY,
  NUM INT
);
